### PR TITLE
Changes apache log location

### PR DESCRIPTION
**Pull request by thatarchguy**
Changes the log location from `other_vhost_access_log.log` or whatever to `postmaster.access.log` and `postmaster.error.log`

Signed-off-by: Kevin <kevin@stealsyour.pw>

### CODE REVIEW

**Comment by PrahlM93** [comment]
@thatarchguy, can we change it to be in /opt/postmaster/logs? That way in Docker deployments the container doesn't grow in size if the logs folder is a mount.

**Comment by thatarchguy** [comment]
I was gonna bring this up in slack, but this works better. I cannot get postmaster to create the app logs. I don't know when this regression started, but I have to manually `touch /opt/postmaster/logs/postmaster.log` & chown it for the logs to start flowing in. 

I can see about redirecting the apache log to that folder.

**Comment by PrahlM93** [comment]
Maybe a permissions issue on the logs directory. I'll investigate.

**Comment by PrahlM93** [comment]
@thatarchguy, I just tested this in Vagrant and PostMaster didn't have a problem creating the log file. Make sure that /opt/postmaster/logs has write privileges from www-data.

**Pull request merged**
